#!/usr/bin/tclsh

#
# \brief  Generate ABI symbol list for a shared library
# \author Norman Feske
# \author Pirmin Duss
# \date   2016-12-07
#
# The tool takes the shared library as argument and writes the output to
# standard output. Each line of the resulting output contains the symbol name,
# type, and size
#

variable tool_dir [file dirname [file normalize [info script]]]

source [file join $tool_dir abi abi_symbols.inc]

abi_symbols_from_library $argv stdout
