
create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/libc \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/posix \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_lxip


build app/large_vfs_lxip_tool

set config {
<config>
	<parent-provides>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="ROM"/>
		<service name="TRACE"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<default caps="120"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="nic_router" caps="200">
		<resource name="RAM" quantum="10M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes"
		        verbose_packets="no">

			<policy label_prefix="echo_server" domain="echo"/>
			<policy label_prefix="sender_receiver" domain="client"/>

			<domain name="echo" interface="10.0.3.1/24">
				<dhcp-server ip_first="10.0.3.5" ip_last="10.0.3.5"/>
			</domain>

			<domain name="client" interface="10.0.4.1/24">
				<dhcp-server ip_first="10.0.4.5" ip_last="10.0.4.50"/>
				<tcp dst="10.0.3.0/24"> <permit-any domain="echo"/> </tcp>
			</domain>
		</config>
	</start>

	<start name="echo_server">
		<binary name="large_vfs_lxip_tool"/>
		<resource name="RAM" quantum="64M"/>
		<config>
			<arg value="echo"/>
			<arg value="--mode"/>
			<arg value="echo_server"/>
			<libc stdout="/dev/log" stderr="/dev/log" socket="/socket"/>
			<vfs>
				<dir name="dev"> <log/> </dir>
				<dir name="socket"> <lxip dhcp="yes"/> </dir>
			</vfs>
		</config>
	</start>

	<start name="sender_receiver-1">
		<binary name="large_vfs_lxip_tool"/>
		<resource name="RAM" quantum="64M"/>
		<config>
			<arg value="sender_receiver"/>
			<arg value="--mode"/>
			<arg value="sender_receiver"/>
			<libc stdout="/dev/log" stderr="/dev/log" socket="/socket"/>
			<vfs>
				<dir name="dev"> <log/> </dir>
				<dir name="socket"> <lxip dhcp="yes"/> </dir>
			</vfs>
		</config>
	</start>

	<start name="sender_receiver-2">
		<binary name="large_vfs_lxip_tool"/>
		<resource name="RAM" quantum="64M"/>
		<config>
			<arg value="sender_receiver"/>
			<arg value="--mode"/>
			<arg value="sender_receiver"/>
			<libc stdout="/dev/log" stderr="/dev/log" socket="/socket"/>
			<vfs>
				<dir name="dev"> <log/> </dir>
				<dir name="socket"> <lxip dhcp="yes"/> </dir>
			</vfs>
		</config>
	</start>

</config>
}

install_config $config

build_boot_image [build_artifacts]

run_genode_until {sender_receiver" exited with exit value 0} 30
