
create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init \
                  [depot_user]/src/libc \
                  [depot_user]/src/linux_nic_drv \
                  [depot_user]/src/linux_rtc_drv \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/openssl \
                  [depot_user]/src/posix \
                  [depot_user]/src/stdcxx \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_pipe \
                  [depot_user]/src/vfs_lxip


build {
	lib/libmosquitto
	lib/libmosquittopp
	lib/jsonc
	test/large_vfs_lxip_tool
}

set config {
<config>
	<parent-provides>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="ROM"/>
		<service name="TRACE"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<default caps="120"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="linux_rtc_drv" caps="200" ld="no">
		<resource name="RAM" quantum="8M"/>
		<provides>
			<service name="Rtc"/>
		</provides>
		<config>
			<nic mac="02:00:00:00:12:11" tap="tap0"/>
		</config>
	</start>

	<start name="linux_nic_drv" caps="200" ld="no">
		<resource name="RAM" quantum="8M"/>
		<config>
			<nic mac="02:00:00:00:12:11" tap="tap0"/>
		</config>
	</start>

	<start name="nic_router" caps="200">
		<resource name="RAM" quantum="10M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes"
		        verbose_packets="no">

			<policy label_prefix="linux_nic_drv" domain="uplink"/>
			<policy label_prefix="mqtt_client"   domain="client"/>

			<domain name="uplink" interface="10.0.2.55/24" gateway="10.0.2.1">
				<nat domain="client"
				     tcp-ports="300"/>
			</domain>

			<domain name="client" interface="10.0.4.1/24">
				<dhcp-server ip_first="10.0.4.5" ip_last="10.0.4.5"/>
				<tcp dst="0.0.0.0/0"> <permit-any domain="uplink"/> </tcp>
			</domain>
		</config>
	</start>

	<start name="mqtt_client" caps="250">
		<binary name="large_vfs_lxip_tool"/>
		<resource name="RAM" quantum="64M"/>
		<config>
			<arg value="mqtt_client"/>
			<libc stdin="/dev/null" stdout="/dev/log" stderr="/dev/log"
			      socket="/socket" rtc="/dev/rtc" pipe="/dev/pipe"/>
			<vfs>
				<dir name="dev">
					<log/> <null/> <rtc/>
					<dir name="pipe"> <pipe/> </dir>
				</dir>
				<dir name="socket"> <lxip dhcp="yes"/> </dir>
			</vfs>
		</config>
	</start>

</config>
}
install_config $config

build_boot_image [build_artifacts]

run_genode_until {sender_receiver" exited with exit value 0} 30
