create_boot_directory

proc depot_user {} { return [get_cmd_arg --depot-user genodelabs] }

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/fonts_fs \
                  [depot_user]/src/themed_decorator \
                  [depot_user]/src/init \
                  [depot_user]/src/floating_window_layouter \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/menu_view \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/wm \
                  [depot_user]/src/zlib

install_config {
<config>
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="TRACE"/>
	</parent-provides>

	<default caps="100"/>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1000">
		<resource name="RAM" quantum="32M" constrain_phys="yes"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides>
			<service name="Input"/> <service name="Framebuffer"/>
		</provides>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Nitpicker"/></provides>
		<config>
			<background color="#123456"/>
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="3" content="client" label="no" hover="always" />

			<policy label_prefix="pointer" domain="pointer"/>
			<default-policy domain="default"/>
		</config>
	</start>

	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
		<route>
			<service name="Nitpicker"> <child name="nitpicker" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="wm" caps="150">
		<resource name="RAM" quantum="2M"/>
		<provides> <service name="Nitpicker"/> </provides>
		<config>
			<policy label_prefix="decorator" role="decorator"/>
			<policy label_prefix="layouter"  role="layouter"/>
		</config>
		<route>
			<service name="ROM" label="resize_request"> <child name="report_rom"/> </service>
			<service name="ROM" label="focus">          <child name="report_rom"/> </service>
			<service name="Report">                     <child name="report_rom"/> </service>
			<service name="Nitpicker"> <child name="nitpicker"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="layouter">
		<binary name="floating_window_layouter"/>
		<resource name="RAM" quantum="2M"/>
		<config/>
		<route>
			<service name="ROM" label="window_list">       <child name="report_rom"/> </service>
			<service name="ROM" label="focus_request">     <child name="report_rom"/> </service>
			<service name="ROM" label="hover">             <child name="report_rom"/> </service>
			<service name="ROM" label="decorator_margins"> <child name="report_rom"/> </service>
			<service name="Report">                        <child name="report_rom"/> </service>
			<service name="Nitpicker">                     <child name="wm"/>         </service>
			<any-service> <child name="wm"/> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="decorator" caps="200">
		<binary name="themed_decorator"/>
		<resource name="RAM" quantum="8M"/>
		<config>
			<libc/>
			<vfs> <tar name="plain_decorator_theme.tar"/> </vfs>
		</config>
		<route>
			<service name="ROM"    label="window_layout">     <child name="report_rom"/> </service>
			<service name="ROM"    label="pointer">           <child name="report_rom"/> </service>
			<service name="Report" label="decorator_margins"> <child name="report_rom"/> </service>
			<service name="Report" label="hover">             <child name="report_rom"/> </service>
			<service name="Nitpicker">                        <child name="wm"/>         </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="2M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes">
			<policy label="menu_view -> dialog"              report="init_status_monitor -> dialog"/>
			<policy label="init_state_monitor -> init_state" report="init -> state"/>
			<policy label="layouter -> window_list"          report="wm -> window_list"/>
			<policy label="layouter -> focus_request"        report="wm -> focus_request"/>
			<policy label="decorator -> window_layout"       report="layouter -> window_layout"/>
			<policy label="wm -> resize_request"             report="layouter -> resize_request"/>
			<policy label="decorator -> pointer"             report="wm -> pointer"/>
			<policy label="layouter -> hover"                report="decorator -> hover"/>
			<policy label="layouter -> decorator_margins"    report="decorator -> decorator_margins"/>
			<policy label="wm -> focus"                      report="layouter -> focus"/>
			<policy label="gui -> config"                    report="manager -> gui_config"/>
			<policy label="nitpicker -> focus"               report="manager -> focus"/>
		</config>
	</start>

	<start name="fonts_fs" caps="300">
		<resource name="RAM" quantum="8M"/>
		<binary name="vfs"/>
		<route>
			<service name="ROM" label="config"> <parent label="fonts_fs.config"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides> <service name="File_system"/> </provides>
	</start>

	<start name="menu_view" caps="200">
		<resource name="RAM" quantum="5M"/>
		<config xpos="20" ypos="10" width="600">
			<libc stderr="/dev/log"/>
			<vfs>
				<tar name="menu_view_styles.tar" />
				<dir name="dev"> <log/> </dir>
				<dir name="fonts"> <fs label="fonts"/> </dir>
			</vfs>
		</config>
		<route>
			<service name="ROM" label="dialog"> <child name="report_rom" /> </service>
			<service name="Report" label="hover"> <child name="report_rom"/> </service>
			<service name="File_system" label="fonts"> <child name="fonts_fs"/> </service>
			<service name="Nitpicker"> <child name="wm"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="init" caps="1500">
		<resource name="RAM" quantum="64M"/>
		<config>
			<parent-provides>
				<service name="PD"/>
				<service name="CPU"/>
				<service name="ROM"/>
				<service name="RM"/>
				<service name="LOG"/>
				<service name="IRQ"/>
				<service name="Timer"/>
			</parent-provides>
			<default-route>
				<any-service> <parent/> <any-child/> </any-service>
			</default-route>
			<report ids="yes" init_ram="yes" init_caps="yes" child_ram="yes" child_caps="yes" requested="no"/>
			<start name="report_rom" caps="100">
				<resource name="RAM" quantum="1M"/>
				<provides> <service name="Report"/> <service name="ROM"/> </provides>
				<config verbose="no"/>
			</start>
			<start name="bomb" caps="100">
				<resource name="RAM" quantum="1M"/>
				<config/>
			</start>
		</config>
		<route>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="init_state_monitor">
		<resource name="RAM" quantum="2M"/>
		<config monitor_caps="yes"/>
		<route>
			<service name="ROM" label="init_state"> <child name="report_rom"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

</config>}

build {
	app/init_state_monitor
	test/bomb
}

build_boot_image {
	init_state_monitor
	bomb
}

run_genode_until forever
